### ISSUE TITLE
Authentication/authorization question

### ISSUE THREAD

**Issue by thangchung** [pekkah/tanka-graphql#102]
Hi @pekkah. How about authentication/authorization if we use this library. I have seen that we have `X-Requested-With` with the value `authorization` at https://github.com/pekkah/tanka-graphql/blob/14fd8d23e39c5063fb372c1eba39dceb250e0caf/samples/graphql.samples.chat.web/Startup.cs#L47. Is it what we do with the key authentication from the client side. With `GraphQL.NET`, there is `https://github.com/graphql-dotnet/authorization` for doing `authn/authz` for the system. My question is how can we do it in this lib or is it planning to do in next phase?

**Comment by pekkah** [comment]
This should get you started https://docs.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-2.2. I'm not going to be building anything similar to graphql-dotnet/authorization as I think that is beyond the scope of this project. I'll try to provide the tools for building similar things but implementation will be up to the user.

**Comment by thangchung** [comment]
@pekkah Yes. Got up. Thank for your clarification.

**Comment by pekkah** [comment]
@thangchung once [this](https://github.com/pekkah/tanka-graphql/blob/feature/directives/tests/graphql.tests/type/DirectiveTypeFacts.cs) lands to master creating similar authorization should be easy

**Comment by thangchung** [comment]
@pekkah I have seen that [`DirectiveType`](https://github.com/pekkah/tanka-graphql/blob/master/src/graphql/type/DirectiveType.cs) and [`DirectiveTypeFacts`](https://github.com/pekkah/tanka-graphql/blob/master/tests/graphql.tests/type/DirectiveTypeFacts.cs) already merged into `master` so when do you plan to have a release for it? And which release version will have it? I'm waiting for trying this cool feature.

**Comment by pekkah** [comment]
Sorry had trouble with Azure DevOps so the builds got stuck. They seem to be running now again.
