### ISSUE TITLE
Add Convenience Middleware for GraphiQL, Playground and Voyager

### ISSUE THREAD

**Issue by maldworth** [pekkah/tanka-graphql#115]
Similar to the graphql-dotnet/server offering

```
// use graphiQL middleware at default url /graphiql
app.UseGraphiQLServer(new GraphiQLOptions());

// use graphql-playground middleware at default url /ui/playground
app.UseGraphQLPlayground(new GraphQLPlaygroundOptions());
    
// use voyager middleware at default url /ui/voyager
app.UseGraphQLVoyager(new GraphQLVoyagerOptions());
```

If this is reasonable, I'd be willing to take a stab at making a PR for this.

**Comment by thangchung** [comment]
@maldworth At the moment, I used libraries from [`server`](https://github.com/graphql-dotnet/server). The project created by @pekkah as well

```csharp
dotnet add package GraphQL.Server.Ui.GraphiQL
dotnet add package GraphQL.Server.Ui.Playground
dotnet add package GraphQL.Server.Ui.Voyager
```

I just think your idea is okay, but if is it some ways like plugins or some kind like that which do not include in the core `tanka`

My usages are at https://github.com/vietnam-devs/coolstore-microservices/blob/master/src/services/graphql/Startup.cs#L103

**Comment by pekkah** [comment]
@maldworth sorry but I'm trying to keep things simple. I don't see benefit in providing a single HTML page inside a nuget package. Maybe in the future I will integrate GraphQL Playground into the server similar to what apollo does but for now that is not on the list of things to do.

**Comment by maldworth** [comment]
@pekkah I understand, thank you

@thangchung Thanks, but the one thing that I want is to be able to prove scaleout with the graphql subscriptions. Right now you do: `app.UseWebSockets();` in order to get the subscriptions working with those three packages included with the GraphQL.Server. So if I viewed any of those three UI in a scaleout scenario, than an event on one of them, would not propagate to the other apis.  So I need a SignalR version of either GraphiQL/Playground/Voyager.

As mentioned, I can do that myself, but thought it would be handy to include it as a package to help others. But I understand, this repo isn't meant to be the main focus, it's the GraphQL.Server.

**Comment by thangchung** [comment]
`app.UseWebSockets();` => Thank you for this point. I have never known that I have used it, just remove it 👍
