### ISSUE TITLE
Optional List on input breaks instrospection in GraphQL client

### ISSUE THREAD

**Issue by qonn** [pekkah/tanka-graphql#339]
In v0.10.0,

Currently, the schema below breaks introspection in GraphQL Clients 
(Tested with GraphQL Playground, Altair GraphQL Client)

### Example Schema

```graphql
input InputItem {
  name: String
  foo: [String]
}

type Mutation {
  createItem(input: InputItem!): ID
}
```

This is due to `defaultValue` being assigned as `System.Object[]`

**Comment by pekkah** [comment]
Thank you for reporting. I found the source and hopefully fixed it.

**Comment by pekkah** [comment]
Here's the matching test https://github.com/pekkah/tanka-graphql/blob/master/tests/graphql.tests/bug/Bug_339.cs. If you could try the beta package when it's finished building and report if your issue is fixed I can tag the release so the fix will go to nuget also.

**Comment by qonn** [comment]
Thank you so much for this :smile:. I've tried the v0.10.1-beta.16 and it works as expected now.
