### ISSUE TITLE
Schema stitching fails to return proper introspection schema with enums.

### ISSUE THREAD

**Issue by qonn** [pekkah/tanka-graphql#361]
In Version 0.10.1,

I am facing an issue while trying to use this functionality with enums. ~~It turns out that the `MergeTool.Schema#L17:13` currently does not support enums.~~

When following the example but with enums on my graphql schema, It says the enums were missing. (GraphQL Playground)

This also occurs on tanka-graphql-samples by simply adding an enum field in `type Channel`.

```graphql
enum ChannelStatus {
  A
  B
  C
}

type Channel {
  id: ID!
  name: String!
  status: ChannelStatus
}

# the rest of schema ...
```

**Comment by pekkah** [comment]
Yep. Will fix it on the weekend.

**Comment by qonn** [comment]
@pekkah Thank you for this.
